# Generated by Django 4.2.5 on 2024-02-15 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shedule_app', '5005_remove_rate_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='source',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Источник'),
        ),
    ]
