# Generated by Django 4.2.5 on 2024-02-16 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shedule_app', '5006_user_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abonements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('is_subscribe', models.BooleanField(default=False, verbose_name='Требует продления?')),
            ],
            options={
                'verbose_name': 'Абонемент',
                'verbose_name_plural': 'Абонементы',
            },
        ),
        migrations.CreateModel(
            name='AbonementJournal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(verbose_name='Дата активации')),
                ('abonement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shedule_app.abonements', verbose_name='Абонемент')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shedule_app.user', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Журнал абонементов',
                'verbose_name_plural': 'Журнал абонементов',
            },
        ),
    ]
