# Generated by Django 4.2.5 on 2024-03-12 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shedule_app', '5009_abonements_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='comment_1',
            field=models.TextField(blank=True, null=True, verbose_name='1ый Комментарий'),
        ),
        migrations.AddField(
            model_name='training',
            name='comment_2',
            field=models.TextField(blank=True, null=True, verbose_name='2ой Комментарий'),
        ),
    ]
