# Generated by Django 4.2.5 on 2024-03-12 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shedule_app', '5010_training_comment_1_training_comment_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='abonementjournal',
            name='end',
            field=models.BooleanField(default=False, null=True, verbose_name='Истёк'),
        ),
    ]
